# Generated by Django 3.1.2 on 2020-11-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'BillItem',
                'verbose_name_plural': 'BillItems',
                'db_table': 'Bill_Item',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('items', models.ManyToManyField(to='shop.BillItem')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'Bill',
                'ordering': ['-dateTime'],
            },
        ),
    ]
