# Generated by Django 3.1.2 on 2020-11-10 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bill_seller', to='shop.seller'),
        ),
    ]
